/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WsAudioPlayer {
        "audio": string;
        "calculateBarWidth": () => Promise<number>;
        "color": string;
        "create": () => Promise<void>;
        "duration": string;
        "enableFullTrackLoop": () => Promise<void>;
        "height": string;
        "playpause": () => Promise<void>;
        "resolution": number;
        "setLoop": (enable: boolean) => Promise<void>;
        "theme": string;
        "title": string;
        "toggleLoop": () => Promise<void>;
    }
}
declare global {
    interface HTMLWsAudioPlayerElement extends Components.WsAudioPlayer, HTMLStencilElement {
    }
    var HTMLWsAudioPlayerElement: {
        prototype: HTMLWsAudioPlayerElement;
        new (): HTMLWsAudioPlayerElement;
    };
    interface HTMLElementTagNameMap {
        "ws-audio-player": HTMLWsAudioPlayerElement;
    }
}
declare namespace LocalJSX {
    interface WsAudioPlayer {
        "audio"?: string;
        "color"?: string;
        "duration"?: string;
        "height"?: string;
        "resolution"?: number;
        "theme"?: string;
        "title"?: string;
    }
    interface IntrinsicElements {
        "ws-audio-player": WsAudioPlayer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ws-audio-player": LocalJSX.WsAudioPlayer & JSXBase.HTMLAttributes<HTMLWsAudioPlayerElement>;
        }
    }
}
